---
- name: Skopeo from Redhat (OpenShift Required)
  command:
    argv:
      - "skopeo copy"
      - "--src-creds {{ src_registry_user }}:{{ src_registry_passwd }}"
      - "docker://{{ src_registry_url }}{{ item }}"
      - "containers-storage:{{ src_registry_url }}{{ item }}"
  changed_when: True
  with_items:
    - "{{ docker_image_list_required }}"
  tags:
    - openshift_required

- name: Skopeo from Redhat (OpenShift Optional)
  command:
    argv:
      - "skopeo copy"
      - "--src-creds {{ src_registry_user }}:{{ src_registry_passwd }}"
      - "docker://{{ src_registry_url }}{{ item }}"
      - "containers-storage:{{ src_registry_url }}{{ item }}"
  changed_when: True
  with_items:
    - "{{ docker_image_list_optional }}"
  tags:
    - openshift_optional

- name: Skopeo from Redhat (OpenShift S2I)
  command:
    argv:
      - "skopeo copy"
      - "--src-creds {{ src_registry_user }}:{{ src_registry_passwd }}"
      - "docker://{{ src_registry_url }}{{ item }}"
      - "containers-storage:{{ src_registry_url }}{{ item }}"
  changed_when: True
  with_items:
    - "{{ docker_image_list_s2i }}"
  tags:
    - openshift_s2i

